spring:
  application:
    name: scIPTV
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: 8080

logging:
  level:
    root: INFO
    com.sciptv: INFO

sciptv:
  playlist:
    source-id: 1
    api-url-template: https://epg.51zmt.top:8001/multicast/api/channels/{sourceId}/
    output-dir: output/playlists
    http-proxy-base-url: ${SCIPTV_HTTP_PROXY_BASE_URL:http://192.168.3.1:8188}
    epg-urls: ${SCIPTV_EPG_URLS:https://epg.51zmt.top:8001/e.xml,https://epg.112114.xyz/pp.xml}
    fcc-address: ${SCIPTV_FCC_ADDRESS:182.139.234.40:8027}
