spring:
  main:
    lazy-initialization: true
  autoconfigure:
    exclude:
      - com.github.xiaoymin.knife4j.spring.configuration.Knife4jAutoConfiguration
      - com.github.xiaoymin.knife4j.spring.configuration.insight.Knife4jInsightAutoConfiguration
      - org.springdoc.webmvc.ui.SwaggerConfig
      - org.springdoc.core.configuration.SpringDocUIConfiguration
      - org.springdoc.webmvc.core.configuration.SpringDocWebMvcConfiguration
      - org.springdoc.webmvc.core.configuration.MultipleOpenApiSupportConfiguration

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

knife4j:
  enable: false
